name: Simple Python CI

# Trigger this workflow on every push and pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install Python dependencies globally
      - name: Install dependencies
        run: |
          pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies

      # Step 4: Run the tests
      - name: Run tests
        run: |
          python -m unittest discover -s test -p "*.py"  # Discover and run all tests in the "test" folder
