name: Simple Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies

      # Step 4: Run tests
      - name: Run tests
        run: |
          pytest movievault/test/  # Explicitly point to the "movievault/test" directory
